sonar.projectKey=devops-demo-app
sonar.projectName=DevOps Demo App
sonar.sources=app
sonar.tests=app/test
sonar.exclusions=app/test/**,venv/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.junit.reportPaths=results.xml